In [36]:
import pandas as pd

In [37]:
df=pd.read_csv("Housing.csv")
df=df.dropna()

In [38]:
df.head(2)

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished

In [39]:
df=pd.get_dummies(df,drop_first=True)

In [40]:
df.head()

price  area  bedrooms  bathrooms  stories  parking  mainroad_yes  \
0  13300000  7420         4          2        3        2          True   
1  12250000  8960         4          4        4        3          True   
2  12250000  9960         3          2        2        2          True   
3  12215000  7500         4          2        2        3          True   
4  11410000  7420         4          1        2        2          True   

   guestroom_yes  basement_yes  hotwaterheating_yes  airconditioning_yes  \
0          False         False                False                 True   
1          False         False                False                 True   
2          False          True                False                False   
3          False          True                False                 True   
4           True          True                False                 True   

   prefarea_yes  furnishingstatus_semi-furnished  furnishingstatus_unfurnished  
0          True                            False                         False  
1         False                            False                         False  
2          True                             True                         False  
3          True                            False                         False  
4         False                            False                         False

In [41]:
x=df.drop('price',axis=1)

In [42]:
y=df['price']

In [43]:
from numpy import size
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [44]:
from sklearn.linear_model import LinearRegression
L=LinearRegression()
l_model=L.fit(x_train,y_train)


In [45]:
l_prediction=l_model.predict(x_test)

In [46]:
l_prediction

array([5164653.90033967, 7224722.29802167, 3109863.24240338,
       4612075.3272256 , 3294646.25725955, 3532275.09556558,
       5611774.56836476, 6368145.98732718, 2722856.95689985,
       2629405.61585782, 9617039.5031558 , 2798087.30447888,
       3171096.76847063, 3394639.09125528, 3681088.65424275,
       5263187.74621485, 3035963.47612384, 4786122.8004005 ,
       4349551.9200572 , 3572362.09930451, 5774875.21395649,
       5886993.57919883, 2730836.19518458, 4727316.47323635,
       5244847.527168  , 7555324.21605603, 3220790.84680268,
       5191898.79934207, 8143726.91009785, 3398814.09825035,
       6490693.05027925, 3315105.9074781 , 6708457.36761326,
       4201738.21071676, 3557571.06735186, 5836974.50478626,
       4808660.67448475, 4362878.73613261, 3191242.95701508,
       4596554.93225238, 4566042.86048411, 3517779.52374148,
       7205844.79365835, 3983597.27861103, 3749338.70271056,
       4274731.09125895, 6757442.10783741, 4037320.43665851,
       3769334.90397126,

In [47]:
x_test.head()

area  bedrooms  bathrooms  stories  parking  mainroad_yes  guestroom_yes  \
316  5900         4          2        2        1         False          False   
77   6500         3          2        3        0          True          False   
360  4040         2          1        1        0          True          False   
90   5000         3          1        2        0          True          False   
493  3960         3          1        1        0          True          False   

     basement_yes  hotwaterheating_yes  airconditioning_yes  prefarea_yes  \
316          True                False                False         False   
77          False                False                 True          True   
360         False                False                False         False   
90          False                False                 True         False   
493         False                False                False         False   

     furnishingstatus_semi-furnished  furnishingstatus_unfurnished  
316                            False                          True  
77                             False                         False  
360                             True                         False  
90                              True                         False  
493                            False                         False

In [48]:
x_test=x_test.reset_index(drop=True)

In [49]:
x_test[0:1]

area  bedrooms  bathrooms  stories  parking  mainroad_yes  guestroom_yes  \
0  5900         4          2        2        1         False          False   

   basement_yes  hotwaterheating_yes  airconditioning_yes  prefarea_yes  \
0          True                False                False         False   

   furnishingstatus_semi-furnished  furnishingstatus_unfurnished  
0                            False                          True

In [50]:
l_model.predict(x_test[0:1])

array([5164653.90033967])

In [51]:
y_test=y_test.reset_index(drop=True)

In [52]:
y_test[0:1]

0    4060000
Name: price, dtype: int64

In [53]:
y_test.head()

0    4060000
1    6650000
2    3710000
3    6440000
4    2800000
Name: price, dtype: int64

In [54]:
from xgboost import XGBRegressor

In [55]:
x=XGBRegressor()
x_model=x.fit(x_train,y_train)

In [56]:
x_model.predict(x_test[0:1])

array([4.5615205e+06], dtype=float32)

In [57]:
x_pre=x_model.predict(x_test)

In [58]:
y_test[0:1]

0    4060000
Name: price, dtype: int64

In [59]:
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

rmse_lr = np.sqrt(mean_squared_error(y_test, l_prediction))
r2_lr = r2_score(y_test, l_prediction)

rmse_xgb = np.sqrt(mean_squared_error(y_test, x_pre))
r2_xgb = r2_score(y_test, x_pre)

print("Linear Regression RMSE:", rmse_lr)
print("Linear Regression R2:", r2_lr)

print("XGBoost RMSE:", rmse_xgb)
print("XGBoost R2:", r2_xgb)

Linear Regression RMSE: 1324506.9600914388
Linear Regression R2: 0.6529242642153184
XGBoost RMSE: 1448271.4858865377
XGBoost R2: 0.5850309133529663


In [62]:
import joblib
joblib.dump(l_model,"lr.pkl")
joblib.dump(x_model,"xg.pkl")

['xg.pkl']

In [63]:
l=joblib.load('lr.pkl')

In [64]:
l.predict(x_test[0:1])

array([5164653.90033967])

In [65]:
y_test[0:1]

0    4060000
Name: price, dtype: int64

In [66]:
x=joblib.load('xg.pkl')

In [67]:
x.predict(x_test[0:1])

array([4.5615205e+06], dtype=float32)